/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedLayoutRouteImport } from './routes/(protected)/_layout'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as protectedLayoutIndexRouteImport } from './routes/(protected)/_layout/index'
import { Route as protectedLayoutTiposTransacaoIndexRouteImport } from './routes/(protected)/_layout/tipos-transacao/index'
import { Route as protectedLayoutLigasIndexRouteImport } from './routes/(protected)/_layout/ligas/index'
import { Route as protectedLayoutClubesIndexRouteImport } from './routes/(protected)/_layout/clubes/index'
import { Route as protectedLayoutAssinaturasIndexRouteImport } from './routes/(protected)/_layout/assinaturas/index'
import { Route as protectedLayoutMercadoContratarRouteImport } from './routes/(protected)/_layout/mercado/contratar'
import { Route as protectedLayoutLigasLigasCriarRouteImport } from './routes/(protected)/_layout/ligas/ligas-criar'
import { Route as protectedLayoutLigasConfiguracoesRouteImport } from './routes/(protected)/_layout/ligas/configuracoes'
import { Route as protectedLayoutJogadoresImagemRouteImport } from './routes/(protected)/_layout/jogadores/imagem'

const protectedLayoutRoute = protectedLayoutRouteImport.update({
  id: '/(protected)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutIndexRoute = protectedLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedLayoutTiposTransacaoIndexRoute =
  protectedLayoutTiposTransacaoIndexRouteImport.update({
    id: '/tipos-transacao/',
    path: '/tipos-transacao/',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedLayoutLigasIndexRoute =
  protectedLayoutLigasIndexRouteImport.update({
    id: '/ligas/',
    path: '/ligas/',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedLayoutClubesIndexRoute =
  protectedLayoutClubesIndexRouteImport.update({
    id: '/clubes/',
    path: '/clubes/',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedLayoutAssinaturasIndexRoute =
  protectedLayoutAssinaturasIndexRouteImport.update({
    id: '/assinaturas/',
    path: '/assinaturas/',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedLayoutMercadoContratarRoute =
  protectedLayoutMercadoContratarRouteImport.update({
    id: '/mercado/contratar',
    path: '/mercado/contratar',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedLayoutLigasLigasCriarRoute =
  protectedLayoutLigasLigasCriarRouteImport.update({
    id: '/ligas/ligas-criar',
    path: '/ligas/ligas-criar',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedLayoutLigasConfiguracoesRoute =
  protectedLayoutLigasConfiguracoesRouteImport.update({
    id: '/ligas/configuracoes',
    path: '/ligas/configuracoes',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedLayoutJogadoresImagemRoute =
  protectedLayoutJogadoresImagemRouteImport.update({
    id: '/jogadores/imagem',
    path: '/jogadores/imagem',
    getParentRoute: () => protectedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof authLoginRoute
  '/': typeof protectedLayoutIndexRoute
  '/jogadores/imagem': typeof protectedLayoutJogadoresImagemRoute
  '/ligas/configuracoes': typeof protectedLayoutLigasConfiguracoesRoute
  '/ligas/ligas-criar': typeof protectedLayoutLigasLigasCriarRoute
  '/mercado/contratar': typeof protectedLayoutMercadoContratarRoute
  '/assinaturas/': typeof protectedLayoutAssinaturasIndexRoute
  '/clubes/': typeof protectedLayoutClubesIndexRoute
  '/ligas/': typeof protectedLayoutLigasIndexRoute
  '/tipos-transacao/': typeof protectedLayoutTiposTransacaoIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/': typeof protectedLayoutIndexRoute
  '/jogadores/imagem': typeof protectedLayoutJogadoresImagemRoute
  '/ligas/configuracoes': typeof protectedLayoutLigasConfiguracoesRoute
  '/ligas/ligas-criar': typeof protectedLayoutLigasLigasCriarRoute
  '/mercado/contratar': typeof protectedLayoutMercadoContratarRoute
  '/assinaturas': typeof protectedLayoutAssinaturasIndexRoute
  '/clubes': typeof protectedLayoutClubesIndexRoute
  '/ligas': typeof protectedLayoutLigasIndexRoute
  '/tipos-transacao': typeof protectedLayoutTiposTransacaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/login': typeof authLoginRoute
  '/(protected)/_layout': typeof protectedLayoutRouteWithChildren
  '/(protected)/_layout/': typeof protectedLayoutIndexRoute
  '/(protected)/_layout/jogadores/imagem': typeof protectedLayoutJogadoresImagemRoute
  '/(protected)/_layout/ligas/configuracoes': typeof protectedLayoutLigasConfiguracoesRoute
  '/(protected)/_layout/ligas/ligas-criar': typeof protectedLayoutLigasLigasCriarRoute
  '/(protected)/_layout/mercado/contratar': typeof protectedLayoutMercadoContratarRoute
  '/(protected)/_layout/assinaturas/': typeof protectedLayoutAssinaturasIndexRoute
  '/(protected)/_layout/clubes/': typeof protectedLayoutClubesIndexRoute
  '/(protected)/_layout/ligas/': typeof protectedLayoutLigasIndexRoute
  '/(protected)/_layout/tipos-transacao/': typeof protectedLayoutTiposTransacaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/jogadores/imagem'
    | '/ligas/configuracoes'
    | '/ligas/ligas-criar'
    | '/mercado/contratar'
    | '/assinaturas/'
    | '/clubes/'
    | '/ligas/'
    | '/tipos-transacao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/jogadores/imagem'
    | '/ligas/configuracoes'
    | '/ligas/ligas-criar'
    | '/mercado/contratar'
    | '/assinaturas'
    | '/clubes'
    | '/ligas'
    | '/tipos-transacao'
  id:
    | '__root__'
    | '/(auth)/login'
    | '/(protected)/_layout'
    | '/(protected)/_layout/'
    | '/(protected)/_layout/jogadores/imagem'
    | '/(protected)/_layout/ligas/configuracoes'
    | '/(protected)/_layout/ligas/ligas-criar'
    | '/(protected)/_layout/mercado/contratar'
    | '/(protected)/_layout/assinaturas/'
    | '/(protected)/_layout/clubes/'
    | '/(protected)/_layout/ligas/'
    | '/(protected)/_layout/tipos-transacao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authLoginRoute: typeof authLoginRoute
  protectedLayoutRoute: typeof protectedLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)/_layout': {
      id: '/(protected)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout/': {
      id: '/(protected)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedLayoutIndexRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/tipos-transacao/': {
      id: '/(protected)/_layout/tipos-transacao/'
      path: '/tipos-transacao'
      fullPath: '/tipos-transacao/'
      preLoaderRoute: typeof protectedLayoutTiposTransacaoIndexRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/ligas/': {
      id: '/(protected)/_layout/ligas/'
      path: '/ligas'
      fullPath: '/ligas/'
      preLoaderRoute: typeof protectedLayoutLigasIndexRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/clubes/': {
      id: '/(protected)/_layout/clubes/'
      path: '/clubes'
      fullPath: '/clubes/'
      preLoaderRoute: typeof protectedLayoutClubesIndexRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/assinaturas/': {
      id: '/(protected)/_layout/assinaturas/'
      path: '/assinaturas'
      fullPath: '/assinaturas/'
      preLoaderRoute: typeof protectedLayoutAssinaturasIndexRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/mercado/contratar': {
      id: '/(protected)/_layout/mercado/contratar'
      path: '/mercado/contratar'
      fullPath: '/mercado/contratar'
      preLoaderRoute: typeof protectedLayoutMercadoContratarRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/ligas/ligas-criar': {
      id: '/(protected)/_layout/ligas/ligas-criar'
      path: '/ligas/ligas-criar'
      fullPath: '/ligas/ligas-criar'
      preLoaderRoute: typeof protectedLayoutLigasLigasCriarRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/ligas/configuracoes': {
      id: '/(protected)/_layout/ligas/configuracoes'
      path: '/ligas/configuracoes'
      fullPath: '/ligas/configuracoes'
      preLoaderRoute: typeof protectedLayoutLigasConfiguracoesRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/jogadores/imagem': {
      id: '/(protected)/_layout/jogadores/imagem'
      path: '/jogadores/imagem'
      fullPath: '/jogadores/imagem'
      preLoaderRoute: typeof protectedLayoutJogadoresImagemRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
  }
}

interface protectedLayoutRouteChildren {
  protectedLayoutIndexRoute: typeof protectedLayoutIndexRoute
  protectedLayoutJogadoresImagemRoute: typeof protectedLayoutJogadoresImagemRoute
  protectedLayoutLigasConfiguracoesRoute: typeof protectedLayoutLigasConfiguracoesRoute
  protectedLayoutLigasLigasCriarRoute: typeof protectedLayoutLigasLigasCriarRoute
  protectedLayoutMercadoContratarRoute: typeof protectedLayoutMercadoContratarRoute
  protectedLayoutAssinaturasIndexRoute: typeof protectedLayoutAssinaturasIndexRoute
  protectedLayoutClubesIndexRoute: typeof protectedLayoutClubesIndexRoute
  protectedLayoutLigasIndexRoute: typeof protectedLayoutLigasIndexRoute
  protectedLayoutTiposTransacaoIndexRoute: typeof protectedLayoutTiposTransacaoIndexRoute
}

const protectedLayoutRouteChildren: protectedLayoutRouteChildren = {
  protectedLayoutIndexRoute: protectedLayoutIndexRoute,
  protectedLayoutJogadoresImagemRoute: protectedLayoutJogadoresImagemRoute,
  protectedLayoutLigasConfiguracoesRoute:
    protectedLayoutLigasConfiguracoesRoute,
  protectedLayoutLigasLigasCriarRoute: protectedLayoutLigasLigasCriarRoute,
  protectedLayoutMercadoContratarRoute: protectedLayoutMercadoContratarRoute,
  protectedLayoutAssinaturasIndexRoute: protectedLayoutAssinaturasIndexRoute,
  protectedLayoutClubesIndexRoute: protectedLayoutClubesIndexRoute,
  protectedLayoutLigasIndexRoute: protectedLayoutLigasIndexRoute,
  protectedLayoutTiposTransacaoIndexRoute:
    protectedLayoutTiposTransacaoIndexRoute,
}

const protectedLayoutRouteWithChildren = protectedLayoutRoute._addFileChildren(
  protectedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authLoginRoute: authLoginRoute,
  protectedLayoutRoute: protectedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
